{% set name = "pymatreader" %}
{% set version = "0.0.30" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8187b6ee77a9b1ec0d8ccae9b22c9031d01104a412737cc4a71e6d993a1a12b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - future
    - h5py
    - numpy
    - python >=3.7
    - scipy !=1.7.0
    - xmltodict

test:
  imports:
    - pymatreader
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/obob/pymatreader
  summary: Convenient reader for Matlab mat files
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - thht
    - hoechenberger
